
            <menu:top id="1" name="制作账户" display="block" rank="">
                <menu:item name="制作账户信息" link="user/index" rank="" />
            </menu:top>
            <menu:top id="2" name="系统设置" display="block" rank="">
                <menu:item name="系统参数管理" link="system/index" rank="admin_info" />
                <menu:item name="管理员帐号管理" link="control/index" rank="admin_main" />
                <menu:item name="在线文件管理" link="filemaster/index" rank="admin_filemaster" />
                <menu:item name="帐号用户组管理" link="group/index" rank="admin_group" />
            </menu:top>
            <menu:top id="2" name="常用维护" display="block" rank="">
                <menu:item name="数据库一键备份" link="database/index" rank="admin_database,admin_database_in" />
                <menu:item name="数据库一键还原" link="database/bak" rank="admin_database,admin_database_out" />
            </menu:top>
            <menu:top id="2" name="在线版本更新" display="block" rank="">
                <menu:item name="一键版本更新" link="updata/index" rank="admin_updata" />
            </menu:top>
            